/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TestNewRouteImport } from './routes/test.new'
import { Route as SchoolsNewRouteImport } from './routes/schools.new'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardSoloRouteImport } from './routes/dashboard.solo'
import { Route as DashboardSchoolRouteImport } from './routes/dashboard.school'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as TestTestIdTakeRouteImport } from './routes/test.$testId.take'
import { Route as TestTestIdResultsRouteImport } from './routes/test.$testId.results'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TestNewRoute = TestNewRouteImport.update({
  id: '/test/new',
  path: '/test/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsNewRoute = SchoolsNewRouteImport.update({
  id: '/schools/new',
  path: '/schools/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSoloRoute = DashboardSoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchoolRoute = DashboardSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DashboardRoute,
} as any)
const TestTestIdTakeRoute = TestTestIdTakeRouteImport.update({
  id: '/test/$testId/take',
  path: '/test/$testId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdResultsRoute = TestTestIdResultsRouteImport.update({
  id: '/test/$testId/results',
  path: '/test/$testId/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/solo': typeof DashboardSoloRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/schools/new': typeof SchoolsNewRoute
  '/test/new': typeof TestNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/test/$testId/results': typeof TestTestIdResultsRoute
  '/test/$testId/take': typeof TestTestIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/solo': typeof DashboardSoloRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/schools/new': typeof SchoolsNewRoute
  '/test/new': typeof TestNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/test/$testId/results': typeof TestTestIdResultsRoute
  '/test/$testId/take': typeof TestTestIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/school': typeof DashboardSchoolRoute
  '/dashboard/solo': typeof DashboardSoloRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/schools/new': typeof SchoolsNewRoute
  '/test/new': typeof TestNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/test/$testId/results': typeof TestTestIdResultsRoute
  '/test/$testId/take': typeof TestTestIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tests'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/solo'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/schools/new'
    | '/test/new'
    | '/dashboard/'
    | '/test/$testId/results'
    | '/test/$testId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tests'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/solo'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/schools/new'
    | '/test/new'
    | '/dashboard'
    | '/test/$testId/results'
    | '/test/$testId/take'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tests'
    | '/dashboard/parent'
    | '/dashboard/school'
    | '/dashboard/solo'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/schools/new'
    | '/test/new'
    | '/dashboard/'
    | '/test/$testId/results'
    | '/test/$testId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TestsRoute: typeof TestsRoute
  SchoolsNewRoute: typeof SchoolsNewRoute
  TestNewRoute: typeof TestNewRoute
  TestTestIdResultsRoute: typeof TestTestIdResultsRoute
  TestTestIdTakeRoute: typeof TestTestIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/test/new': {
      id: '/test/new'
      path: '/test/new'
      fullPath: '/test/new'
      preLoaderRoute: typeof TestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/new': {
      id: '/schools/new'
      path: '/schools/new'
      fullPath: '/schools/new'
      preLoaderRoute: typeof SchoolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solo': {
      id: '/dashboard/solo'
      path: '/solo'
      fullPath: '/dashboard/solo'
      preLoaderRoute: typeof DashboardSoloRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/school': {
      id: '/dashboard/school'
      path: '/school'
      fullPath: '/dashboard/school'
      preLoaderRoute: typeof DashboardSchoolRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/test/$testId/take': {
      id: '/test/$testId/take'
      path: '/test/$testId/take'
      fullPath: '/test/$testId/take'
      preLoaderRoute: typeof TestTestIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId/results': {
      id: '/test/$testId/results'
      path: '/test/$testId/results'
      fullPath: '/test/$testId/results'
      preLoaderRoute: typeof TestTestIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardParentRoute: typeof DashboardParentRoute
  DashboardSchoolRoute: typeof DashboardSchoolRoute
  DashboardSoloRoute: typeof DashboardSoloRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardParentRoute: DashboardParentRoute,
  DashboardSchoolRoute: DashboardSchoolRoute,
  DashboardSoloRoute: DashboardSoloRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TestsRoute: TestsRoute,
  SchoolsNewRoute: SchoolsNewRoute,
  TestNewRoute: TestNewRoute,
  TestTestIdResultsRoute: TestTestIdResultsRoute,
  TestTestIdTakeRoute: TestTestIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
